services:
  mongodb:
    image: mongo:latest
    command: mongod --bind_ip_all --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      scoutly-net:
        ipv4_address: 172.20.0.10
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: |
        mongosh --eval "
          try {
            db = db.getSiblingDB('admin');
            db.auth('${MONGODB_ROOT_USERNAME}', '${MONGODB_ROOT_PASSWORD}');
            if (db.runCommand('ping').ok) {
              process.exit(0);
            } else {
              process.exit(1);
            }
          } catch (e) {
            process.exit(1);
          }
        "
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      - app
      - mongodb
    networks:
      - scoutly-net

  app:
    build: .
    networks:
      scoutly-net:
        ipv4_address: 172.20.0.11
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
      - NODE_ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    shm_size: 2gb
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  scoutly-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
