services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: |
        mongosh --eval "
          try {
            if (db.getMongo().getDBs().databases.length > 0) {
              process.exit(0);
            } else {
              process.exit(1);
            }
          } catch (e) {
            process.exit(1);
          }
        "
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env.local
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
      - mongodb

  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/scoutly
      - NODE_ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    shm_size: 2gb
    restart: unless-stopped

volumes:
  mongodb_data:
