services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/scoutly
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEXT_PUBLIC_SKIP_AUTH=${NEXT_PUBLIC_SKIP_AUTH}
      - NEXT_PUBLIC_DEV_USER_EMAIL=${NEXT_PUBLIC_DEV_USER_EMAIL}
      - NEXT_PUBLIC_DEV_USER_NAME=${NEXT_PUBLIC_DEV_USER_NAME}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    shm_size: 2gb

volumes:
  mongodb_data:
