import {connectDB, disconnectDB} from '../config/database';
import {CompanyService} from '../services/companyService';
import {WorkModel} from '../models/Company';

const companies = [
	{
		companyID: '37signals',
		company: '37signals',
		careers_url: 'https://37signals.com/jobs/',
		selector: '.jobs__container',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Chicago, USA',
		office_locations: [],
		fields: ['software development', 'productivity tools'],
		openToApplication: false,
	},
	{
		companyID: '84codes',
		company: '84codes',
		careers_url: 'https://www.84codes.com/career/',
		selector: '.positions',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Stockholm, Sweden',
		office_locations: [],
		fields: ['cloud infrastructure', 'messaging systems'],
		openToApplication: true,
	},
	{
		companyID: 'aha',
		company: 'Aha!',
		careers_url: 'https://www.aha.io/company/careers/current-openings',
		selector: '.JobsHome',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['product management', 'roadmapping'],
		openToApplication: false,
	},
	{
		companyID: 'ashby',
		company: 'Ashby',
		careers_url:
			'https://www.ashbyhq.com/careers?ashby_department_id=2c32d70f-d7cb-4a06-bd87-048084e3eb10',
		selector: '._content_ud4nd_71 ',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['recruiting', 'HR tech'],
		openToApplication: true,
	},
	{
		companyID: 'atlassian',
		company: 'Atlassian',
		careers_url:
			'https://www.atlassian.com/company/careers/all-jobs?team=Engineering&location=&search=',
		selector: '.careers',
		work_model: WorkModel.HYBRID,
		headquarters: 'Sydney, Australia',
		office_locations: [
			'San Francisco, USA',
			'Mountain View, USA',
			'New York, USA',
			'Amsterdam, Netherlands',
			'Manila, Philippines',
			'Bengaluru, India',
		],
		fields: ['software development', 'collaboration tools'],
		openToApplication: false,
	},
	{
		companyID: 'automattic',
		company: 'Automattic',
		careers_url: 'https://automattic.com/jobs/',
		selector: '.job-posts',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['WordPress', 'web publishing'],
		openToApplication: false,
	},
	{
		companyID: 'awesome_motive',
		company: 'Awesome Motive',
		careers_url: 'https://awesomemotive.com/careers/#positions',
		selector: '#positions',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'West Palm Beach, USA',
		office_locations: [],
		fields: ['WordPress', 'digital marketing'],
		openToApplication: false,
	},
	{
		companyID: 'agency_analytics',
		company: 'AgencyAnalytics',
		careers_url: 'https://agencyanalytics.com/company/careers#openings',
		selector: '#openings',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Toronto, Canada',
		office_locations: [],
		fields: ['analytics', 'reporting tools'],
		openToApplication: true,
	},

	{
		companyID: 'buffer',
		company: 'Buffer',
		careers_url: 'https://buffer.com/journey#open-roles',
		selector: '#open-roles',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['social media', 'marketing tools'],
		openToApplication: true,
	},
	{
		companyID: 'buddyboss',
		company: 'BuddyBoss',
		careers_url: 'https://www.buddyboss.com/careers/#work-with-us',
		selector: '#work-with-us',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Vancouver, Canada',
		office_locations: [],
		fields: ['WordPress', 'community platforms'],
		openToApplication: true,
	},
	{
		companyID: 'buildkite',
		company: 'Buildkite',
		careers_url: 'https://buildkite.com/about/careers/#open-roles',
		selector: '#open-roles',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Melbourne, Australia',
		office_locations: [],
		fields: ['CI/CD', 'developer tools'],
		openToApplication: true,
	},
	{
		companyID: 'chef',
		company: 'Chef',
		careers_url:
			'https://www.progress.com/company/careers?category=Software%20Engineering&remoteType=Remote',
		selector: '#jobs',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Seattle, USA',
		office_locations: [],
		fields: ['DevOps', 'automation'],
		openToApplication: false,
	},
	{
		companyID: 'clipboard_health',
		company: 'Clipboard Health',
		careers_url:
			'https://job-boards.greenhouse.io/clipboardhealth?gh_src=b2e829504us&departments%5B%5D=4013035004',
		selector: '.job-posts',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['healthcare', 'staffing'],
		openToApplication: false,
	},
	{
		companyID: 'cloudbeds',
		company: 'Cloudbeds',
		careers_url: 'https://www.cloudbeds.com/careers/',
		selector: '.job-post-section',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Diego, USA',
		office_locations: ['São Paulo, Brazil', 'Dublin, Ireland'],
		fields: ['hospitality', 'SaaS'],
		openToApplication: false,
	},
	{
		companyID: 'datadog',
		company: 'DataDog',
		careers_url:
			'https://careers.datadoghq.com/engineering/?remote%5B0%5D=Remote',
		selector: '#job-openings',
		work_model: WorkModel.HYBRID,
		headquarters: 'New York, USA',
		office_locations: ['Paris, France', 'Boston, USA', 'Dublin, Ireland'],
		fields: ['monitoring', 'analytics', 'cloud'],
		openToApplication: false,
	},
	{
		companyID: 'deel',
		company: 'Deel',
		careers_url:
			'https://jobs.ashbyhq.com/Deel?__hsfp=1088227782&__hssc=29278755.1.1744444410156&__hstc=29278755.b60185cebc5d7be2af7df7c982273dc2.1744444410156.1744444410156.1744444410156.1&departmentId=8c27e7fa-f898-4de1-adf6-70c67c1e1c11',
		selector: '.ashby-job-posting-brief-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['HR tech', 'payroll', 'compliance'],
		openToApplication: false,
	},
	{
		companyID: 'dnsimple',
		company: 'DNSimple',
		careers_url: 'https://dnsimple.com/jobs',
		selector: '.whr-items',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['DNS management', 'domain services'],
		openToApplication: false,
	},
	{
		companyID: 'doist',
		company: 'Doist',
		careers_url: 'https://doist.com/careers#open-roles',
		selector: '#open-roles',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['productivity', 'task management'],
		openToApplication: true,
	},
	{
		companyID: 'dribbble',
		company: 'Dribbble',
		careers_url: 'https://dribbble.com/careers',
		selector: '#BambooHR',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['design', 'creative community'],
		openToApplication: false,
	},
	{
		companyID: 'duckduckgo',
		company: 'DuckDuckGo',
		careers_url: 'https://duckduckgo.com/hiring',
		selector: '.careers_openPositions__K2zeJ',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Paoli, USA',
		office_locations: [],
		fields: ['search engine', 'privacy'],
		openToApplication: false,
	},
	{
		companyID: 'elastic',
		company: 'Elastic',
		careers_url: 'https://jobs.elastic.co/jobs/department/engineering?#/',
		selector: '#job-container',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Mountain View, USA',
		office_locations: [
			'Amsterdam, Netherlands',
			'London, UK',
			'Berlin, Germany',
		],
		fields: ['search', 'observability', 'security'],
		openToApplication: false,
	},
	{
		companyID: 'envato',
		company: 'Envato',
		careers_url:
			'https://jobs.lever.co/envato-2?department=Technology&team=Engineering',
		selector: '.postings-group',
		work_model: WorkModel.HYBRID,
		headquarters: 'Melbourne, Australia',
		office_locations: ['Los Angeles, USA'],
		fields: ['digital assets', 'creative marketplace'],
		openToApplication: false,
	},
	{
		companyID: 'eyeo',
		company: 'Eyeo',
		careers_url: 'https://eyeo.com/careers?department=23243030',
		selector: '.jobs-block',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Cologne, Germany',
		office_locations: [],
		fields: ['ad blocking', 'web privacy'],
		openToApplication: false,
	},
	{
		companyID: 'gitbook',
		company: 'GitBook',
		careers_url: 'https://careers.gitbook.com/',
		selector: "data-testid='table-of-contents'",
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Paris, France',
		office_locations: [],
		fields: ['documentation', 'knowledge management'],
		openToApplication: false,
	},
	{
		companyID: 'gradle',
		company: 'Gradle',
		careers_url: 'https://gradle.com/careers/#open-roles',
		selector: '#open-roles',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['build automation', 'developer tools'],
		openToApplication: false,
	},
	{
		companyID: 'helpscout',
		company: 'Help Scout',
		careers_url: 'https://www.helpscout.com/company/careers/',
		selector: '.LpSectionstyles__LpSectionSECTION',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Boston, USA',
		office_locations: [],
		fields: ['customer support', 'helpdesk'],
		openToApplication: true,
	},
	{
		companyID: 'hotjar',
		company: 'Hotjar',
		careers_url:
			'https://jobs.lever.co/contentsquare/?department=Engineering%2C%20Product%2C%20and%20Design&workplaceType=remote',
		selector: '.postings-wrapper',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Malta',
		office_locations: [],
		fields: ['analytics', 'user feedback'],
		openToApplication: false,
	},
	{
		companyID: 'hubstaff',
		company: 'Hubstaff',
		careers_url: 'https://hubstaff.com/jobs#hsds-open-positions',
		selector: '.postings-wrapper',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Indianapolis, USA',
		office_locations: [],
		fields: ['time tracking', 'productivity'],
		openToApplication: false,
	},
	{
		companyID: 'miro',
		company: 'Miro',
		careers_url:
			'https://miro.com/careers/open-positions/?department=4099198002',
		selector: '.PositionsList_wrapper__la_JY',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['design', 'collaboration'],
		openToApplication: false,
	},

	{
		companyID: 'kraken',
		company: 'Kraken',
		careers_url:
			'https://jobs.ashbyhq.com/kraken.com?departmentId=5f67bd79-103b-4ac1-8d79-952b45ea47c9',
		selector: '._departments_12ylk_345',
		work_model: WorkModel.HYBRID,
		headquarters: 'San Francisco, USA',
		office_locations: ['London, UK', 'Singapore'],
		fields: ['cryptocurrency', 'fintech'],
		openToApplication: false,
	},
	{
		companyID: 'labster',
		company: 'Labster',
		careers_url: 'https://careers.labster.com/jobs',
		selector: '.z-career-jobs-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Copenhagen, Denmark',
		office_locations: ['Zurich, Switzerland', 'Boston, USA'],
		fields: ['education', 'virtual labs'],
		openToApplication: false,
	},
	{
		companyID: 'mailerlite',
		company: 'MailerLite',
		careers_url: 'https://www.mailerlite.com/jobs',
		selector: '.positions-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Vilnius, Lithuania',
		office_locations: [],
		fields: ['email marketing', 'SaaS'],
	},

	// TODO: continue here
	{
		companyID: 'mango_languages',
		company: 'Mango Languages',
		careers_url: 'https://mangolanguages.com/careers',
		selector: '.careers-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Detroit, USA',
		office_locations: [],
		fields: ['language learning', 'education'],
	},
	{
		companyID: 'mozilla',
		company: 'Mozilla',
		careers_url: 'https://careers.mozilla.org',
		selector: '.position-list',
		work_model: WorkModel.HYBRID,
		headquarters: 'Mountain View, USA',
		office_locations: [
			'San Francisco, USA',
			'Portland, USA',
			'Toronto, Canada',
			'Berlin, Germany',
		],
		fields: ['open source', 'browser development'],
	},
	{
		companyID: 'netlify',
		company: 'Netlify',
		careers_url: 'https://www.netlify.com/careers',
		selector: '.jobs-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['web development', 'JAMstack'],
	},
	{
		companyID: 'olark',
		company: 'Olark',
		careers_url: 'https://www.olark.com/about#jobs',
		selector: '.positions-container',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['live chat', 'customer support'],
	},
	{
		companyID: 'onthegosystems',
		company: 'OnTheGoSystems',
		careers_url: 'https://onthegosystems.com/jobs',
		selector: '.jobs-listing',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['WordPress', 'translation tools'],
	},
	{
		companyID: 'oyster_hr',
		company: 'Oyster HR',
		careers_url: 'https://www.oysterhr.com/careers',
		selector: '.career-opportunities',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'London, UK',
		office_locations: [],
		fields: ['HR tech', 'global employment'],
	},
	{
		companyID: 'overleaf',
		company: 'Overleaf',
		careers_url: 'https://www.overleaf.com/jobs',
		selector: '.positions-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'London, UK',
		office_locations: [],
		fields: ['LaTeX', 'document collaboration'],
	},
	{
		companyID: 'particular',
		company: 'Particular Software',
		careers_url: 'https://particular.net/Careers',
		selector: '.job-listings',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['distributed systems', 'messaging'],
	},
	{
		companyID: 'percona',
		company: 'Percona',
		careers_url: 'https://www.percona.com/about-percona/careers',
		selector: '.careers-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Durham, USA',
		office_locations: [],
		fields: ['database', 'open source'],
	},
	{
		companyID: 'planetscale',
		company: 'PlanetScale',
		careers_url: 'https://planetscale.com/careers',
		selector: '.jobs-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['database', 'cloud infrastructure'],
	},
	{
		companyID: 'platform_sh',
		company: 'Platform.sh',
		careers_url: 'https://platform.sh/company/careers',
		selector: '.positions-wrapper',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Paris, France',
		office_locations: [],
		fields: ['cloud hosting', 'PaaS'],
	},
	{
		companyID: 'powertofly',
		company: 'PowerToFly',
		careers_url: 'https://powertofly.com/careers',
		selector: '.job-listings',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: [],
		fields: ['diversity recruiting', 'career platform'],
	},
	{
		companyID: 'prezly',
		company: 'Prezly',
		careers_url: 'https://careers.prezly.com',
		selector: '.open-positions',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Brussels, Belgium',
		office_locations: [],
		fields: ['PR software', 'communications'],
	},
	{
		companyID: 'protocol_labs',
		company: 'Protocol Labs',
		careers_url: 'https://protocol.ai/join',
		selector: '.job-openings',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['blockchain', 'distributed systems'],
	},
	{
		companyID: 'red_hat',
		company: 'Red Hat',
		careers_url: 'https://www.redhat.com/en/jobs',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Raleigh, USA',
		office_locations: [
			'Boston, USA',
			'Brno, Czech Republic',
			'Bangalore, India',
		],
		fields: ['Linux', 'open source', 'cloud'],
	},
	{
		companyID: 'redox',
		company: 'Redox',
		careers_url: 'https://www.redoxengine.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Madison, USA',
		office_locations: [],
		fields: ['healthcare', 'data integration'],
	},
	{
		companyID: 'rebelmouse',
		company: 'RebelMouse',
		careers_url: 'https://careers.rebelmouse.com',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: [],
		fields: ['CMS', 'web publishing'],
	},
	{
		companyID: 'remote',
		company: 'Remote (Remote.com)',
		careers_url: 'https://remote.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['HR tech', 'global employment'],
	},
	{
		companyID: 'requis',
		company: 'Requis',
		careers_url: 'https://requis.com/company/join/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['supply chain', 'marketplace'],
	},
	{
		companyID: 'saas_group',
		company: 'SaaS.group',
		careers_url: 'https://saas.group/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['SaaS', 'software development'],
	},
	{
		companyID: 'scylladb',
		company: 'ScyllaDB',
		careers_url: 'https://www.scylladb.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Palo Alto, USA',
		office_locations: ['Tel Aviv, Israel'],
		fields: ['database', 'distributed systems'],
	},
	{
		companyID: 'semaphore',
		company: 'Semaphore CI',
		careers_url: 'https://semaphoreci.com/hiring',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Belgrade, Serbia',
		office_locations: [],
		fields: ['CI/CD', 'developer tools'],
	},
	{
		companyID: 'shopify',
		company: 'Shopify',
		careers_url: 'https://www.shopify.com/careers',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Ottawa, Canada',
		office_locations: [
			'Toronto, Canada',
			'Montreal, Canada',
			'Waterloo, Canada',
			'Dublin, Ireland',
		],
		fields: ['e-commerce', 'fintech'],
	},
	{
		companyID: 'shogun',
		company: 'Shogun',
		careers_url: 'https://getshogun.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Palo Alto, USA',
		office_locations: [],
		fields: ['e-commerce', 'page builder'],
	},
	{
		companyID: 'skillcrush',
		company: 'Skillcrush',
		careers_url: 'https://skillcrush.breezy.hr',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['education', 'tech learning'],
	},
	{
		companyID: 'sketch',
		company: 'Sketch',
		careers_url: 'https://www.sketch.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'The Hague, Netherlands',
		office_locations: [],
		fields: ['design', 'design tools'],
	},
	{
		companyID: 'sonatype',
		company: 'Sonatype',
		careers_url: 'https://www.sonatype.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Fulton, USA',
		office_locations: ['London, UK'],
		fields: ['security', 'software supply chain'],
	},
	{
		companyID: 'sourcegraph',
		company: 'Sourcegraph',
		careers_url: 'https://sourcegraph.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['code search', 'developer tools'],
	},
	{
		companyID: 'spotify',
		company: 'Spotify',
		careers_url: 'https://www.lifeatspotify.com',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Stockholm, Sweden',
		office_locations: [
			'New York, USA',
			'London, UK',
			'Stockholm, Sweden',
			'Singapore',
		],
		fields: ['music streaming', 'audio platform'],
	},
	{
		companyID: 'square',
		company: 'Square (Block)',
		careers_url: 'https://careers.squareup.com',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'San Francisco, USA',
		office_locations: [
			'New York, USA',
			'Atlanta, USA',
			'Toronto, Canada',
			'Melbourne, Australia',
		],
		fields: ['fintech', 'payments'],
	},
	{
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'San Francisco, USA',
		office_locations: [
			'Dublin, Ireland',
			'London, UK',
			'Singapore',
			'Tokyo, Japan',
		],
		fields: ['fintech', 'payments'],
	},
	{
		companyID: 'superside',
		company: 'Superside',
		careers_url: 'https://careers.superside.com',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['design', 'creative services'],
	},
	{
		companyID: 'sword_health',
		company: 'Sword Health',
		careers_url: 'https://swordhealth.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: ['Porto, Portugal'],
		fields: ['healthcare', 'digital therapy'],
	},
	{
		companyID: 'time_doctor',
		company: 'Time Doctor',
		careers_url: 'https://www.timedoctor.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['time tracking', 'productivity'],
	},
	{
		companyID: 'toggl',
		company: 'Toggl',
		careers_url: 'https://jobs.toggl.com',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Tallinn, Estonia',
		office_locations: [],
		fields: ['time tracking', 'project management'],
	},
	{
		companyID: 'toptal',
		company: 'Toptal',
		careers_url: 'https://www.toptal.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['talent network', 'freelance platform'],
	},
	{
		companyID: 'turing',
		company: 'Turing',
		careers_url: 'https://www.turing.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Palo Alto, USA',
		office_locations: [],
		fields: ['talent network', 'developer hiring'],
	},
	{
		companyID: 'uscreen',
		company: 'Uscreen',
		careers_url: 'https://www.uscreen.tv/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Washington DC, USA',
		office_locations: [],
		fields: ['video streaming', 'content monetization'],
	},
	{
		companyID: 'wikimedia',
		company: 'Wikimedia Foundation',
		careers_url: 'https://wikimediafoundation.org/about/jobs',
		selector: '.list-view',
		work_model: WorkModel.HYBRID,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['non-profit', 'open knowledge'],
	},
	{
		companyID: 'xapo',
		company: 'Xapo',
		careers_url: 'https://xapo.com/careers',
		selector: '.careers-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Gibraltar',
		office_locations: [],
		fields: ['cryptocurrency', 'digital banking'],
	},
	{
		companyID: 'ynab',
		company: 'YNAB (You Need A Budget)',
		careers_url: 'https://www.youneedabudget.com/careers',
		selector: '.positions-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Lehi, USA',
		office_locations: [],
		fields: ['personal finance', 'budgeting'],
	},
	{
		companyID: 'zapier',
		company: 'Zapier',
		careers_url: 'https://zapier.com/jobs',
		selector: '.jobs-list',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['automation', 'integration platform'],
	},
	{
		companyID: 'zyte',
		company: 'Zyte (Scrapinghub)',
		careers_url: 'https://www.zyte.com/careers',
		selector: '.job-positions',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['web scraping', 'data extraction'],
	},
	{
		companyID: 'booking',
		company: 'Booking.com',
		careers_url:
			'https://jobs.booking.com/booking/jobs?keywords=engineer&sortBy=relevance',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Amsterdam, Netherlands',
		office_locations: [
			'Amsterdam, Netherlands',
			'Manchester, UK',
			'Shanghai, China',
		],
		fields: ['travel', 'accommodation'],
	},
	{
		companyID: 'pachama',
		company: 'Pachama',
		careers_url: 'https://pachama.com/careers/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['climate tech', 'carbon markets'],
	},
	{
		companyID: 'mural',
		company: 'MURAL',
		careers_url: 'https://job-boards.greenhouse.io/mural',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: ['Buenos Aires, Argentina'],
		fields: ['collaboration', 'visual workspace'],
	},
	{
		companyID: 'elevate_labs',
		company: 'Elevate Labs',
		careers_url: 'https://jobs.lever.co/elevatelabs?team=Engineering',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['education', 'brain training'],
	},
	{
		companyID: 'localyze',
		company: 'Localyze',
		careers_url: 'https://www.localyze.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Hamburg, Germany',
		office_locations: [],
		fields: ['HR tech', 'relocation'],
	},
	{
		companyID: 'customer_io',
		company: 'Customer.io',
		careers_url: 'https://customer.io/careers/#open-positions',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Portland, USA',
		office_locations: [],
		fields: ['marketing automation', 'customer messaging'],
	},
	{
		companyID: 'builder_io',
		company: 'Builder.io',
		careers_url: 'https://www.builder.io/m/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['visual development', 'headless CMS'],
	},
	{
		companyID: 'memberful',
		company: 'Memberful',
		careers_url: 'https://memberful.com/jobs/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Chicago, USA',
		office_locations: [],
		fields: ['membership', 'subscription management'],
	},
	{
		companyID: 'blueconic',
		company: 'BlueConic',
		careers_url: 'https://www.blueconic.com/about/careers/open-positions',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Boston, USA',
		office_locations: ['Amsterdam, Netherlands'],
		fields: ['CDP', 'marketing technology'],
	},
	{
		companyID: 'databees',
		company: 'DataBees',
		careers_url: 'https://getdatabees.zohorecruit.com/jobs/Careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['data enrichment', 'B2B data'],
	},
	{
		companyID: 'bejamas',
		company: 'Bejamas',
		careers_url: 'https://bejamas.traffit.com/career/#opportunities',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['JAMstack', 'web development'],
	},
	{
		companyID: 'mailersend',
		company: 'MailerSend',
		careers_url: 'https://www.mailersend.com/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['email service', 'transactional email'],
	},
	{
		companyID: 'modus_create',
		company: 'Modus Create',
		careers_url: 'https://moduscreate.com/careers/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Reston, USA',
		office_locations: [],
		fields: ['digital transformation', 'consulting'],
	},
	{
		companyID: 'contra',
		company: 'Contra',
		careers_url: 'https://contra.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: [],
		fields: ['freelance platform', 'professional network'],
	},
	{
		companyID: 'namecheap',
		company: 'Namecheap',
		careers_url: 'https://www.namecheap.com/careers/openings/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Phoenix, USA',
		office_locations: [],
		fields: ['domain registrar', 'web hosting'],
	},
	{
		companyID: 'pickfu',
		company: 'PickFu',
		careers_url: 'https://pickfu.recruitee.com/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['market research', 'user testing'],
	},
	{
		companyID: 'status',
		company: 'Status',
		careers_url: 'https://status.app/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['status page', 'incident management'],
	},
	{
		companyID: 'whitespectre',
		company: 'Whitespectre',
		careers_url: 'https://www.whitespectre.com/careers/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Barcelona, Spain',
		office_locations: [],
		fields: ['product development', 'consulting'],
	},
	{
		companyID: 'stickermule',
		company: 'Sticker Mule',
		careers_url: 'https://www.stickermule.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: [],
		fields: ['custom printing', 'e-commerce'],
	},
	{
		companyID: 'streak',
		company: 'Streak',
		careers_url: 'https://www.streak.com/careers#open',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['CRM', 'email tools'],
	},
	{
		companyID: 'cinder',
		company: 'Cinder',
		careers_url: 'https://jobs.ashbyhq.com/cinder',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['engineering operations', 'developer tools'],
	},
	{
		companyID: 'bottomless',
		company: 'Bottomless',
		careers_url: 'https://careers.bottomless.com/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Seattle, USA',
		office_locations: [],
		fields: ['IoT', 'coffee subscription'],
	},
	{
		companyID: 'quicktrials',
		company: 'QuickTrials',
		careers_url: 'https://www.quicktrials.com/open-jobs/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['clinical trials', 'healthcare tech'],
	},
	{
		companyID: 'bonfire',
		company: 'Bonfire',
		careers_url: 'https://careers.bonfire.com/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Richmond, USA',
		office_locations: [],
		fields: ['custom merchandise', 'e-commerce'],
	},
	{
		companyID: 'mmhmm',
		company: 'mmhmm',
		careers_url: 'https://www.mmhmm.app/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['video presentation', 'collaboration'],
	},
	{
		companyID: 'timezest',
		company: 'TimeZest',
		careers_url: 'https://www-timezest-com.breezy.hr/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['scheduling', 'productivity'],
	},
	{
		companyID: 'assembly',
		company: 'Assembly',
		careers_url: 'https://assemblyhq.com/job-openings/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['team management', 'collaboration'],
	},
	{
		companyID: 'tyk',
		company: 'Tyk',
		careers_url: 'https://tyk.io/current-vacancies/?category=engineering',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'London, UK',
		office_locations: ['Singapore', 'Atlanta, USA'],
		fields: ['API management', 'API gateway'],
	},
	{
		companyID: 'nethermind',
		company: 'Nethermind',
		careers_url: 'https://job-boards.eu.greenhouse.io/nethermind',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'London, UK',
		office_locations: [],
		fields: ['blockchain', 'ethereum'],
	},
	{
		companyID: 'rebilly',
		company: 'Rebilly',
		careers_url: 'https://www.rebilly.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Montreal, Canada',
		office_locations: [],
		fields: ['fintech', 'subscription billing'],
	},
	{
		companyID: 'tldv',
		company: 'tl;dv',
		careers_url:
			'https://tldv.notion.site/Come-work-at-tl-dv-8da9921dfaaa40d68450790a09d81efe',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Berlin, Germany',
		office_locations: [],
		fields: ['video collaboration', 'meeting tools'],
	},
	{
		companyID: 'pitch',
		company: 'Pitch',
		careers_url: 'https://pitch.com/jobs',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Berlin, Germany',
		office_locations: ['Berlin, Germany'],
		fields: ['presentation software', 'collaboration'],
	},
	{
		companyID: 'slite',
		company: 'Slite',
		careers_url: 'https://slite.com/jobs#open-jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Paris, France',
		office_locations: [],
		fields: ['documentation', 'knowledge management'],
	},
	{
		companyID: 'hackernoon',
		company: 'Hacker Noon',
		careers_url: 'https://careers.hackernoon.com/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['tech publishing', 'content platform'],
	},
	{
		companyID: 'designstripe',
		company: 'DesignStripe',
		careers_url: 'https://designstripe.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['design tools', 'illustration'],
	},
	{
		companyID: 'pocket_worlds',
		company: 'Pocket Worlds',
		careers_url:
			'https://pocketworlds.notion.site/Open-positions-ae368383a74e4d75a7cb751e4de7644b',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['gaming', 'virtual worlds'],
	},
	{
		companyID: 'kona',
		company: 'Kona',
		careers_url: 'https://www.heykona.com/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['employee experience', 'team culture'],
	},
	{
		companyID: 'standard_notes',
		company: 'Standard Notes',
		careers_url: 'https://standardnotes.com/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['note taking', 'privacy'],
	},
	{
		companyID: 'guilded',
		company: 'Guilded',
		careers_url: 'https://www.guilded.gg/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['gaming', 'community platform'],
	},
	{
		companyID: 'revenuecat',
		company: 'RevenueCat',
		careers_url: 'https://job-boards.greenhouse.io/revenuecat',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['subscription management', 'developer tools'],
	},
	{
		companyID: 'make',
		company: 'Make',
		careers_url: 'https://make.recruitee.com/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Prague, Czech Republic',
		office_locations: [],
		fields: ['automation', 'integration platform'],
	},
	{
		companyID: '10up',
		company: '10up',
		careers_url: 'https://10up.com/careers/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['web development', 'WordPress'],
	},
	{
		companyID: 'bestself',
		company: 'BestSelf',
		careers_url: 'https://apply.workable.com/bestself/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['productivity', 'personal development'],
	},
	{
		companyID: 'xwp',
		company: 'XWP',
		careers_url: 'https://xwp.co/about/careers/#open-positions',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['WordPress', 'web development'],
	},
	{
		companyID: 'weaviate',
		company: 'Weaviate',
		careers_url: 'https://careers.weaviate.io/jobs',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Amsterdam, Netherlands',
		office_locations: [],
		fields: ['vector database', 'machine learning'],
	},
	{
		companyID: 'runway',
		company: 'Runway',
		careers_url:
			'https://job-boards.greenhouse.io/runwayml?departments%5B%5D=4010359005',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'New York, USA',
		office_locations: [],
		fields: ['AI', 'creative tools'],
	},
	{
		companyID: 'alpaca',
		company: 'Alpaca',
		careers_url: 'https://alpaca.markets/hiring#alpaca-hiring',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'San Francisco, USA',
		office_locations: [],
		fields: ['fintech', 'trading API'],
	},
	{
		companyID: 'unsplash',
		company: 'Unsplash',
		careers_url: 'https://unsplash.com/hiring',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Montreal, Canada',
		office_locations: [],
		fields: ['photography', 'creative platform'],
	},
	{
		companyID: 'meetedgar',
		company: 'MeetEdgar',
		careers_url: 'https://meetedgar.com/careers/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['social media', 'automation'],
	},
	{
		companyID: 'contentsquare',
		company: 'Contentsquare',
		careers_url: 'https://contentsquare.com/jobs/',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Paris, France',
		office_locations: ['New York, USA', 'London, UK', 'Tel Aviv, Israel'],
		fields: ['analytics', 'user experience'],
	},
	{
		companyID: 'openzeppelin',
		company: 'OpenZeppelin',
		careers_url:
			'https://boards.greenhouse.io/embed/job_board?for=openzeppelin',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['blockchain', 'smart contracts'],
	},
	{
		companyID: 'jamie',
		company: 'Jamie',
		careers_url:
			'https://meetjamie.notion.site/Work-at-jamie-6078dad30d2847ae873f5c272766e1a0',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['fintech', 'financial services'],
	},
	{
		companyID: 'paymentology',
		company: 'Paymentology',
		careers_url: 'https://www.paymentology.com/about-us/careers',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'London, UK',
		office_locations: ['Dubai, UAE', 'Singapore'],
		fields: ['fintech', 'payment processing'],
	},
	{
		companyID: 'attractions_io',
		company: 'Attractions.io',
		careers_url: 'https://attractions.io/careers',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Norwich, UK',
		office_locations: [],
		fields: ['mobile apps', 'visitor experience'],
	},
	{
		companyID: 'doctorly',
		company: 'Doctorly',
		careers_url: 'https://doctorlycareer.kenjo.io/',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Berlin, Germany',
		office_locations: [],
		fields: ['healthtech', 'practice management'],
	},
	{
		companyID: 'checkin',
		company: 'Check-in',
		careers_url: 'https://group.checkin.com/careers/',
		selector: '',
		work_model: WorkModel.HYBRID,
		headquarters: 'Copenhagen, Denmark',
		office_locations: ['London, UK'],
		fields: ['travel tech', 'hospitality'],
	},
	{
		companyID: 'systemseed',
		company: 'SystemSeed',
		careers_url: 'https://systemseed.com/join-us',
		selector: '',
		work_model: WorkModel.FULLY_REMOTE,
		headquarters: 'Remote',
		office_locations: [],
		fields: ['web development', 'consulting'],
	},
];

async function seedCompanies() {
	try {
		await connectDB();
		console.log('Connected to database');

		// Clear existing companies
		await CompanyService.deleteMany();
		console.log('Cleared existing companies');

		// Insert new companies
		const companiesToCreate = companies.map(company => ({
			companyID: company.companyID!,
			company: company.company!,
			careers_url: company.careers_url!,
			selector: company.selector,
			work_model: company.work_model,
			headquarters: company.headquarters,
			office_locations: company.office_locations,
			fields: company.fields,
		}));

		const createdCompanies = await CompanyService.bulkCreateCompanies(
			companiesToCreate,
		);
		console.log(`Successfully seeded ${createdCompanies.length} companies`);

		await disconnectDB();
		console.log('Database connection closed');
	} catch (error) {
		console.error('Error seeding companies:', error);
		await disconnectDB();
		process.exit(1);
	}
} // Run the seed function
seedCompanies();
